In [1]:
import pickle
import torch

In [3]:
dataset = 'toys'
path_data = '../datasets/data/' + dataset + '/dataset.pkl'
with open(path_data, 'rb') as f:
    data_raw = pickle.load(f)

In [6]:
print(data_raw.keys())

dict_keys(['train', 'val', 'test', 'umap', 'smap'])


In [78]:
train = data_raw['train']
print(train[100])
train

[1235, 1295, 1053, 855, 1000, 156, 562, 832, 613, 856, 1036, 1296, 158, 1297, 1298, 1299, 1168]


{0: [1, 2, 3],
 1: [4, 5, 6],
 2: [9, 10, 11, 12, 4, 5, 13],
 3: [4, 16, 17],
 4: [4, 20, 21, 22, 23, 24, 25, 26, 27, 28],
 5: [31, 32, 33, 34, 35, 36, 37, 38, 4, 39, 5, 6],
 6: [41, 4, 42, 43, 44],
 7: [47, 48, 49, 50, 51, 4],
 8: [4, 5, 6, 13],
 9: [55, 4, 56, 57, 58],
 10: [61, 4, 62],
 11: [65, 66, 67, 68, 69, 70, 71, 72, 4, 73, 74, 75, 38, 76, 77],
 12: [26, 80, 81, 82, 83, 84, 85],
 13: [86, 87, 88, 27, 89, 90, 91, 92, 93, 4, 5],
 14: [95,
  96,
  97,
  4,
  30,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  82,
  107,
  39,
  108,
  109,
  110,
  111,
  48,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132],
 15: [4, 135, 136, 137, 138, 139, 140, 5, 40],
 16: [142, 143, 4, 5],
 17: [145, 51, 146, 147],
 18: [150, 151, 152],
 19: [145,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167],
 20: [169,
  170,
  171,
  172,
  173

In [73]:
id_seq = {}
def split_onebyone():
# 分割成了最小长度为2的交互递增序列
    idx = 0
    for user_temp, seq_temp in train.items():
        for star in range(len(seq_temp)-1):
            id_seq[idx] = seq_temp[:star+2]
            idx += 1
split_onebyone()

In [74]:
id_seq

{0: [1, 2],
 1: [1, 2, 3],
 2: [4, 5],
 3: [4, 5, 6],
 4: [9, 10],
 5: [9, 10, 11],
 6: [9, 10, 11, 12],
 7: [9, 10, 11, 12, 4],
 8: [9, 10, 11, 12, 4, 5],
 9: [9, 10, 11, 12, 4, 5, 13],
 10: [4, 16],
 11: [4, 16, 17],
 12: [4, 20],
 13: [4, 20, 21],
 14: [4, 20, 21, 22],
 15: [4, 20, 21, 22, 23],
 16: [4, 20, 21, 22, 23, 24],
 17: [4, 20, 21, 22, 23, 24, 25],
 18: [4, 20, 21, 22, 23, 24, 25, 26],
 19: [4, 20, 21, 22, 23, 24, 25, 26, 27],
 20: [4, 20, 21, 22, 23, 24, 25, 26, 27, 28],
 21: [31, 32],
 22: [31, 32, 33],
 23: [31, 32, 33, 34],
 24: [31, 32, 33, 34, 35],
 25: [31, 32, 33, 34, 35, 36],
 26: [31, 32, 33, 34, 35, 36, 37],
 27: [31, 32, 33, 34, 35, 36, 37, 38],
 28: [31, 32, 33, 34, 35, 36, 37, 38, 4],
 29: [31, 32, 33, 34, 35, 36, 37, 38, 4, 39],
 30: [31, 32, 33, 34, 35, 36, 37, 38, 4, 39, 5],
 31: [31, 32, 33, 34, 35, 36, 37, 38, 4, 39, 5, 6],
 32: [41, 4],
 33: [41, 4, 42],
 34: [41, 4, 42, 43],
 35: [41, 4, 42, 43, 44],
 36: [47, 48],
 37: [47, 48, 49],
 38: [47, 48, 49, 5

In [35]:
val = data_raw['val']
val[100]

[1247]

In [36]:
test = data_raw['test']
test[100]

[1300]

In [37]:
umap = data_raw['umap']
print(umap[100])
len(umap)

99


19412

In [40]:
smap = data_raw['smap']
print(smap[100])
len(smap)

100


11924

In [26]:
for user_temp, seq_temp in train.items():
    print(user_temp, seq_temp)
    

0 [1, 2, 3]
1 [4, 5, 6]
2 [9, 10, 11, 12, 4, 5, 13]
3 [4, 16, 17]
4 [4, 20, 21, 22, 23, 24, 25, 26, 27, 28]
5 [31, 32, 33, 34, 35, 36, 37, 38, 4, 39, 5, 6]
6 [41, 4, 42, 43, 44]
7 [47, 48, 49, 50, 51, 4]
8 [4, 5, 6, 13]
9 [55, 4, 56, 57, 58]
10 [61, 4, 62]
11 [65, 66, 67, 68, 69, 70, 71, 72, 4, 73, 74, 75, 38, 76, 77]
12 [26, 80, 81, 82, 83, 84, 85]
13 [86, 87, 88, 27, 89, 90, 91, 92, 93, 4, 5]
14 [95, 96, 97, 4, 30, 98, 99, 100, 101, 102, 103, 104, 105, 106, 82, 107, 39, 108, 109, 110, 111, 48, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]
15 [4, 135, 136, 137, 138, 139, 140, 5, 40]
16 [142, 143, 4, 5]
17 [145, 51, 146, 147]
18 [150, 151, 152]
19 [145, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167]
20 [169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 145, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 

In [65]:
a = torch.ones((2,2))
sum(a)

tensor([2., 2.])

In [66]:
import einops

In [67]:
einops.rearrange(a,'a b->(a b)')

tensor([1., 1., 1., 1.])

In [68]:
a

tensor([[1., 1.],
        [1., 1.]])

In [81]:
from tqdm import tqdm

def beautify_tqdm(iterable, desc='', total=None, ncols=100, mininterval=0.1, **kwargs):
    """
    返回一个美化的 tqdm 进度条。

    :param iterable: 可迭代对象（如列表、range等）
    :param desc: 进度条前缀文本
    :param total: 进度条的总数量
    :param ncols: 进度条的宽度
    :param mininterval: 进度条更新的最小时间间隔
    :param kwargs: 其他参数传递给 tqdm
    :return: 返回美化后的 tqdm 进度条
    """
    # 使用 tqdm 初始化进度条
    bar = tqdm(iterable, desc=desc, total=total, ncols=ncols, mininterval=mininterval, **kwargs)

    # 设置进度条的颜色和样式
    bar.set_description(f'\033[1;32;40m{desc}\033[0m')  # 设置描述为绿色
    bar.set_bar_format(
        '{l_bar}{bar}| {n_fmt}/{total_fmt} [elapsed: {elapsed} remaining: {remaining}]'
    )  # 设置进度条格式

    # 自定义美化后的进度条样式
    bar.set_postfix_str('')  # 清除后缀
    return bar

# 使用示例
if __name__ == "__main__":
    for i in beautify_tqdm(range(100), desc="Processing", unit="item"):
        # 模拟任务
        pass



Processing:   0%|          | 0/100 [01:51<?, ?item/s]                     | 0/100 [00:00<?, ?item/s]


AttributeError: 'tqdm' object has no attribute 'set_bar_format'